from app.models import db, Review, environment, SCHEMA
from sqlalchemy.sql import text


def seed_reviews():
    reviews = [
        {"reviewer_id": 2, "restaurant_id": 1, "rating": 4,
         "message": "Nobody at a fast food restaurant treats you like the only customer they care about, but here, that's how you feel. Drive Thru attentive, no mistakes on my order at this location, and they don't push you about meals and drinks. They let you order at your comfort and convenience. This is how it should be."},
        {"reviewer_id": 1, "restaurant_id": 1, "rating": 5,
         "message": "McDonald's is my go-to spot for a quick and satisfying meal. The classic Big Mac never disappoints, and their fries are always perfectly crispy. Fast service and a reliable menu make it a comfort food haven!"},
        {"reviewer_id": 4, "restaurant_id": 1, "rating": 2,
         "message": "Visited this McDonald's during lunchtime, and the long lines were a bit overwhelming. It took quite a while to get my order, and the restaurant was a bit messy. They could use some better organization during peak hours."},
        {"reviewer_id": 2, "restaurant_id": 1, "rating": 4,
         "message": "I appreciate that McDonald's offers healthier options now. The salads are surprisingly good, and the yogurt parfaits are a guilt-free treat. It's nice to have choices beyond the usual fast-food fare."},
        {"reviewer_id": 5, "restaurant_id": 1, "rating": 3,
         "message": "Stopped by McDonald's for a quick bite, and while the service was speedy, my order was a bit mixed up. The staff, however, were very apologetic and quickly fixed the issue. Kudos for the great customer service."},
        {"reviewer_id": 6, "restaurant_id": 1, "rating": 4,
         "message": "The delivery was surprisingly fast, and my Big Mac combo arrived still warm and delicious. "},

        {"reviewer_id": 2, "restaurant_id": 2, "rating": 5,
         "message": "Had a fantastic time at Gyu-Karu! The ambiance is modern and inviting, and the waitstaff is attentive. The assortment of meats and veggies for grilling satisfied both meat lovers and vegetarians in our group."},
        {"reviewer_id": 1, "restaurant_id": 2, "rating": 2,
         "message": "The BBQ meats were dry and lacked the tenderness I had experienced before. Hopefully, they can improve the consistency of their delivery orders."},
        {"reviewer_id": 6, "restaurant_id": 2, "rating": 4,
         "message": "Gyu-Karu never disappoints! The sizzle of meat on the grill and the aroma of the sauces create an immersive dining experience. The variety of dipping sauces adds a personalized touch to each bite. A must-visit for BBQ lovers!"},
        {"reviewer_id": 4, "restaurant_id": 2, "rating": 5,
         "message": "A great option for those craving high-quality Japanese BBQ without leaving home!"},
        {"reviewer_id": 9, "restaurant_id": 2, "rating": 2,
         "message": "The food arrived late, and unfortunately, the quality didn't match up to my expectations."},

        {"reviewer_id": 9, "restaurant_id": 3, "rating": 3,
         "message": "Great service but long line wait"},
        {"reviewer_id": 1, "restaurant_id": 3, "rating": 4,
         "message": "Loved the convenience of location and ordering to go. Hamburgers were delicious."},
        {"reviewer_id": 14, "restaurant_id": 3, "rating": 5,
         "message": "Fast delivery and excellent burger and frozen vanilla custard."},
        {"reviewer_id": 10, "restaurant_id": 3, "rating": 1,
         "message": "Never delivered. Takes forever."},

        {"reviewer_id": 1, "restaurant_id": 4, "rating": 4,
            "message": "Haven't had in a decade and still tastes delicious!"},
        {"reviewer_id": 3, "restaurant_id": 4, "rating": 3,
         "message": "I wish my food was a little hotter upon arrival, but the food was still delicious. Thanks"},
        {"reviewer_id": 12, "restaurant_id": 4, "rating": 5,
         "message": "The delivery person was speedy and nice."},

        {"reviewer_id": 1, "restaurant_id": 5, "rating": 5,
         "message": "Best Americana hot or cold anywhere!"},
        {"reviewer_id": 4, "restaurant_id": 5, "rating": 5,
         "message": "Absolutely love Starbucks! Their coffee is always consistent and the staff is friendly. My go-to place for my daily caffeine fix"},
        {"reviewer_id": 1, "restaurant_id": 5, "rating": 2,
         "message": "Disappointed with my recent experience at Starbucks. The latte I ordered was lukewarm and tasted watered down. Hope they improve their quality control."},
        {"reviewer_id": 5, "restaurant_id": 5, "rating": 4,
         "message": "Their mobile ordering is convenient, and the drinks are usually prepared well. Sometimes the wait can be long during peak hours."},
        {"reviewer_id": 3, "restaurant_id": 5, "rating": 5,
         "message": "Starbucks has a wide variety of delicious drinks. Their caramel macchiato is my favorite. The service is usually fast, and I appreciate their cozy atmosphere."},

        {"reviewer_id": 8, "restaurant_id": 6, "rating": 4,
         "message": "It's close and easy to order and fast delivery."},
        {"reviewer_id": 1, "restaurant_id": 6, "rating": 5,
         "message": "Fantastic. Fresh and hot."},
        {"reviewer_id": 11, "restaurant_id": 6, "rating": 5,
         "message": "Taco Tuesday!!!"},

        {"reviewer_id": 1, "restaurant_id": 7, "rating": 5,
         "message": "Delicious and Quick! Panda Express on Flavor Eats never disappoints. The orange chicken is always crispy and flavorful, and the chow mein is the perfect balance of noodles and veggies. It arrived hot and fresh, and the delivery was faster than expected. Definitely my go-to for a satisfying Chinese food craving."},
        {"reviewer_id": 7, "restaurant_id": 7, "rating": 4,
         "message": "Quick and Tasty! Panda Express on Flavor Eats is my guilty pleasure. The Kung Pao Chicken has the right amount of kick, and the Beijing Beef is sweet and savory in every bite. "},
        {"reviewer_id": 13, "restaurant_id": 7, "rating": 4,
         "message": "Flavorful Options, Slightly Delayed. The food from Panda Express is always packed with flavor, and their variety is impressive. However, my recent order through Flavor Eats arrived about 15 minutes later than the estimated time, which resulted in the food being a bit cooler than I would have liked. "},

        {"reviewer_id": 2, "restaurant_id": 8, "rating": 4,
         "message": "The salad here is very fresh and delicious. My go to lunch place :)"},
        {"reviewer_id": 1, "restaurant_id": 8, "rating": 4,
         "message": "I love this place. The quality of the food and ingredients is exceptional, and the flavor combinations and variety are amazing. Happily ordering again."},
        {"reviewer_id": 6, "restaurant_id": 8, "rating": 1,
         "message": "Terrible Salad Experience. I ordered a salad through Flavor Eats from this place, and it was a huge disappointment. "},
        {"reviewer_id": 11, "restaurant_id": 8, "rating": 2,
         "message": "I had high hopes for a healthy meal when I ordered a salad, but unfortunately, it fell short of my expectations. The portion was small, and the ingredients didn't seem very fresh."},

        {"reviewer_id": 1, "restaurant_id": 9, "rating": 5,
         "message": "The place I went a hundread times during my coding bootcamp. Lots of memories. Thank you!"},
        {"reviewer_id": 2, "restaurant_id": 9, "rating": 4,
         "message": "The Adana Kebab is beautifully seasoned and the hummus is just sooooo good, it's light in flavor compared to store-bought."},
        {"reviewer_id": 10, "restaurant_id": 9, "rating": 3,
         "message": "Not Impressed. The salad I received from this place via Flavor Eats was just okay. "},

        {"reviewer_id": 4, "restaurant_id": 10, "rating": 3,
         "message": "Looks like they changed the crust to a mariposa one? \nNot bad for days you want take out. Steep pricing… $35 for a fairly small thin crust pizza but at least I'm not being lied to or poisoned with gluten"},
        {"reviewer_id": 1, "restaurant_id": 10, "rating": 5,
         "message": "As the name implies, it's all gluten free. And I think it's great pizza. Definitely on my go-to list when I have given up on the idea of making dinner for the fourth time this week. I'm a big fan of the Pollo pizza as well. This place is worth a shot."},
        {"reviewer_id": 8, "restaurant_id": 10, "rating": 1,
         "message": "My recent order of the Gluten Free Garden Pizza from Flavor Eats left me utterly disappointed. I had high hopes for a tasty gluten-free option, but unfortunately, this pizza fell far short of expectations.\nI wouldn't recommend this option to anyone looking for a flavorful gluten-free meal."},

        {"reviewer_id": 12, "restaurant_id": 11, "rating": 4,
         "message": "My boyfriend and I have visited Sharetea a handful of times now and we really enjoy it."},
        {"reviewer_id": 11, "restaurant_id": 11, "rating": 3,
         "message": "I really like taro milk but this one was very okay. It felt watered down, and the the sugar was sooo low. I normally do 50% everywhere but this one felt lower than that. The place was extremely packed so maybe their taro tea milk is something you want to skip and order something else. I gave it a 3 star because the people were super nice and the place is clean and organized."},
        {"reviewer_id": 14, "restaurant_id": 11, "rating": 4,
         "message": "Always nice to find a sharetea everywhere I travel to. It wasn't easy to find parking here but I didn't care. I just wanted by fresh milk matcha tea."},
        {"reviewer_id": 7, "restaurant_id": 11, "rating": 5,
         "message": "It was pretty good tea the little tea bubble things were tasty nothing was really amazing but the food was served quick and the service was friendly. As usual I think the service the speed of it and how friendly the staff is is more important to the product itself because there's always possibility that something could go wrong but everything was great."},
        {"reviewer_id": 5, "restaurant_id": 11, "rating": 5,
         "message": "It was yummy! I would def come here again!"},
        {"reviewer_id": 1, "restaurant_id": 11, "rating": 5,
         "message": "I love bubble tea and Sharetea is hands down one of my two favorite bubble tea places. I would definitely consider myself a regular as well as an addict. One of the main reasons I like Sharetea so much is because of how generous they are with the amount of pearls that they add to their drinks."},

        {"reviewer_id": 1, "restaurant_id": 12, "rating": 5,
         "message": "Outstanding flavors! Ordered a variety of dishes from this restaurant on Flavor Eats, and each one was a delight. The attention to detail in presentation and taste was evident. Highly recommend their dishes!"},
        {"reviewer_id": 3, "restaurant_id": 12, "rating": 4,
         "message": "Consistently good. Have ordered from this restaurant multiple times on Flavor Eats, and they've maintained their quality each time. The taste is great, and the delivery is reliable. A solid option for a convenient and tasty meal."},
        {"reviewer_id": 7, "restaurant_id": 12, "rating": 1,
         "message": "Unimpressed. The food looked nothing like the pictures, and the taste was far from what I expected. A waste of money, unfortunately."},
        {"reviewer_id": 11, "restaurant_id": 12, "rating": 1,
         "message": "Terrible experience. The order was incorrect, and the customer service was unresponsive. Not the kind of service I expected when ordering through Flavor Eats."},
        {"reviewer_id": 13, "restaurant_id": 12, "rating": 4,
         "message": "Solid food quality and quick delivery. The restaurant on Flavor Eats offers a decent selection, and the food arrived well-packaged and still warm. Only deducted a star because one dish was slightly overcooked, but overall a good experience."},
        {"reviewer_id": 8, "restaurant_id": 12, "rating": 4,
         "message": "Delicious flavors, some room for improvement."},

        {"reviewer_id": 2, "restaurant_id": 13, "rating": 4,
         "message": "We went to pick up an order and the service was quick. I like that the hand rolls are wrapped in plastic so the seaweed doesn't get soggy. The set comes with edamame and soup. The sushi quality isn't the best, but okay for a quick meal."},
        {"reviewer_id": 1, "restaurant_id": 13, "rating": 3,
         "message": "I consider myself a sushi connoisseur and MakiMaki was just ok."},
        {"reviewer_id": 6, "restaurant_id": 13, "rating": 4,
         "message": "I really enjoyed my sushi from here. We ordered for delivery and I had the blue crab with avocado roll and the salmon avocado roll. The fish was very fresh. I was given packs of soy sauce and a pack of wasabi."},
        {"reviewer_id": 5, "restaurant_id": 13, "rating": 2,
         "message": "The service was painfully slow, and the staff seemed disinterested in attending to customers."},

        {"reviewer_id": 1, "restaurant_id": 14, "rating": 4,
         "message": "You get a lot of food compared to other places. And it's always good."},
        {"reviewer_id": 11, "restaurant_id": 14, "rating": 4,
         "message": "Can always rely on the Grilled Chicken Caesar Salad to be fresh and plentifiul!"},
        {"reviewer_id": 8, "restaurant_id": 14, "rating": 3,
         "message": "The menu had a good variety of options, from salads to burgers to pasta. But a little pricy."},
        {"reviewer_id": 10, "restaurant_id": 14, "rating": 2,
         "message": "While the food quality was generally good, the prices seemed a bit higher than other similar restaurants on Flavor Eats."},
        {"reviewer_id": 1, "restaurant_id": 14, "rating": 5,
         "message": "I ordered the Neighborhood Burger with fries, and it was delicious! The burger was juicy and well-cooked, and the fries were crispy and seasoned just right."},

        {"reviewer_id": 4, "restaurant_id": 15, "rating": 5,
         "message": "Seafood Lover's Paradise! The Lobster Place is a hidden gem for seafood enthusiasts. The selection is impressive, and the freshness of their offerings is unmatched. I had the pleasure of indulging in their succulent lobster rolls - bursting with flavor and served in a buttery, perfectly toasted bun. The staff's knowledge and enthusiasm for seafood made the experience even better."},
        {"reviewer_id": 2, "restaurant_id": 15, "rating": 2,
         "message": "Overcooked lobster, off-tasting shrimp - not worth the price at all."},
        {"reviewer_id": 1, "restaurant_id": 15, "rating": 5,
         "message": "If you're craving high-quality seafood, this is the place to go!"},

        {"reviewer_id": 1, "restaurant_id": 16, "rating": 4,
         "message": "Sugar, Spice and everything nice!"},
        {"reviewer_id": 5, "restaurant_id": 16, "rating": 4,
         "message": "Red Hot Chilli Pepper is a gem for anyone seeking vegan and halal Indian cuisine. The flavors are authentic and the presentation is spot on."},
        {"reviewer_id": 12, "restaurant_id": 16, "rating": 3,
         "message": "I had high hopes for Red Hot Chilli Pepper, but I found the food to be a bit underwhelming."},

        {"reviewer_id": 5, "restaurant_id": 17, "rating": 3,
         "message": "I love and enjoy unique and interesting flavors, although would've liked some kind of Indian sauce as the base. I had to add Butter sauce to it.."},
        {"reviewer_id": 1, "restaurant_id": 17, "rating": 4,
         "message": "The chicken tikka was absolutely fire."},

        {"reviewer_id": 1, "restaurant_id": 18, "rating": 4,
         "message": "Great food, reasonably priced."},
        {"reviewer_id": 12, "restaurant_id": 18, "rating": 4,
         "message": "I love Chipotle ,because of their fresh salsas. I do feel that they should calm down on the sodium. There is a lot of salt in the chips and especially in the guacamole. that should not be happening however, I still love ordering from them. Thank you!"},
        {"reviewer_id": 8, "restaurant_id": 18, "rating": 5,
         "message": "Everything was great. Temp was good, food was good."},
        {"reviewer_id": 9, "restaurant_id": 18, "rating": 4,
         "message": "Fresh and healthy!"},

        {"reviewer_id": 5, "restaurant_id": 19, "rating": 5,
         "message": "Good quality food - prepared well"},
        {"reviewer_id": 1, "restaurant_id": 19, "rating": 4,
         "message": "Just downstairs. Very convenient."},
        {"reviewer_id": 3, "restaurant_id": 19, "rating": 4,
         "message": "Enjoyed the unique Indo-Chinese fusion at Inchin's Bamboo Garden. Manchurian Cauliflower was a hit. Service was good, just a bit of a wait."},
        {"reviewer_id": 1, "restaurant_id": 19, "rating": 4,
         "message": "Hakka Noodles were a standout. Modern ambiance, a fusion food haven."},

        {"reviewer_id": 1, "restaurant_id": 20, "rating": 5,
         "message": "Mas Veggies is a vegan dream! Their tacos are bursting with flavor. A must-try for plant-based foodies."},
        {"reviewer_id": 10, "restaurant_id": 20, "rating": 3,
         "message": "Decent vegan choices, but portions were smaller than expected. Tasty nonetheless."},
        {"reviewer_id": 11, "restaurant_id": 20, "rating": 4,
         "message": "Mas Veggies nailed it! Tejano burrito was so satisfying. Finally, vegan options that hit the spot."},

        {"reviewer_id": 1, "restaurant_id": 21, "rating": 5,
         "message": "Their cakes are a work of art. Highly recommend the strawberry cake!"},
        {"reviewer_id": 9, "restaurant_id": 21, "rating": 3,
         "message": "Decent options, but my latte was lukewarm when it arrived. Pastries were good though."},
        {"reviewer_id": 13, "restaurant_id": 21, "rating": 5,
         "message": "Perfect breakfast spot! Their Signature Roll Cake is my go-to. Quick delivery too."},
        {"reviewer_id": 1, "restaurant_id": 21, "rating": 5,
         "message": "Paris Baguette is a treat. The rainbow cake is colorful and tasty. Definitely ordering again."},

        {"reviewer_id": 1, "restaurant_id": 22, "rating": 5,
         "message": "The best one that I have ever had. For sure that I will reorder food from this restaurant. Really satisfied! 5 stars for each dish."},
        {"reviewer_id": 4, "restaurant_id": 22, "rating": 5,
         "message": "Healthy and yummy."},
        {"reviewer_id": 11, "restaurant_id": 22, "rating": 5,
         "message": "The bowls were so delicious, and it felt good to eat such high quality fresh food."},
        {"reviewer_id": 12, "restaurant_id": 22, "rating": 4,
         "message": "Amazing flavor, just the right amount of food. I have no complaints and have been going back at least once a week now."},
        {"reviewer_id": 9, "restaurant_id": 22, "rating": 5,
         "message": "Delicious, doesnt feel heavy after, would purchase again."},
        {"reviewer_id": 1, "restaurant_id": 22, "rating": 5,
         "message": "Twice in one week, repeat customer in the future!!"},
        {"reviewer_id": 3, "restaurant_id": 22, "rating": 4,
         "message": "Food was really tasty and portion size was a lot. Thank you moon owls for the delicious food and Flavor eats for having the pick up order ready within a few minutes of ordering"},

        {"reviewer_id": 5, "restaurant_id": 23, "rating": 4,
         "message": "Spaghetti and meatball craving...you can't go wrong with their delicious tomato sauce and perfectly sized meatballs"},
        {"reviewer_id": 1, "restaurant_id": 23, "rating": 5,
         "message": "Amazing tasty and presentation"},
        {"reviewer_id": 12, "restaurant_id": 23, "rating": 2,
         "message": "Mixed feelings about Caffe Roma. While the atmosphere is charming, the prices are on the higher side for what you get."},
        {"reviewer_id": 8, "restaurant_id": 23, "rating": 2,
         "message": "Caffe Roma needs improvement. The pizza lacked the flavor I expected, and the fish I ordered was dry. I've had better experiences elsewhere for the same price."},

        {"reviewer_id": 1, "restaurant_id": 24, "rating": 4,
         "message": "We have been eating here for years, moved away and still order only from here! Everything is delicious"},
        {"reviewer_id": 6, "restaurant_id": 24, "rating": 4,
         "message": "Star of India is simply the best! Food is always fresh, hot and tasty."},
        {"reviewer_id": 5, "restaurant_id": 24, "rating": 4,
         "message": "Their Masala Sauce is very rich and savory and not overly sweet/tomatoey like lots of others in town. Excellent!"},

        {"reviewer_id": 1, "restaurant_id": 25, "rating": 4,
         "message": "It's good stuff love the neat safe packaging and organic options"},
        {"reviewer_id": 2, "restaurant_id": 25, "rating": 5,
         "message": "Had a lovely breakfast experience at ORGANICO. Would definitely recommend to health-conscious foodies."},
        {"reviewer_id": 5, "restaurant_id": 25, "rating": 5,
         "message": " The coffee is smooth, and they offer non-dairy milk options. It's a wonderful place for those looking for organic and plant-based breakfast choices."},
        {"reviewer_id": 3, "restaurant_id": 25, "rating": 2,
         "message": "I expected better quality for the price. The ambiance was nice, but the food left me disappointed."},
        {"reviewer_id": 10, "restaurant_id": 25, "rating": 2,
         "message": "While the concept is great, the execution needs improvement."},

    ]

    seed_reviews = [db.session.add(
        Review(**review)) for review in reviews]
    db.session.commit()


def undo_reviews():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM reviews"))

    db.session.commit()
